### ISSUE TITLE
New zone prompt stays up after pressing Yes

### ISSUE THREAD

**Issue by aa-chrismcfadyen** [dratr/loggerhead#3]
It does record your choice in the addon options and starts logging, the prompt just stays on the screen.

I haven't tried pressing no, as I've only done a few new dungeons, and they were on difficulties I wanted to log.

I'm also not 100% sure it isn't caused by another addon, as I had a couple errors pop up when zoning in

**Comment by dratr** [comment]
Hi - thanks for the report -- I have been using in both mythic and heroic dungeons in DF without seeing this issue.  If you can reproduce with other addons (especially those triggering errors) enabled, please reopen and also include one or more zones where you see it occur.
Thanks!

**Comment by aa-chrismcfadyen** [comment]
I finally decided to go back and do some test cases because I got tired of the r.io addon doing an inconsistent job of enabling logging.  I can't reopen this ticket, but if you don't end up seeing this, I'll create a new one.

I used Ruby Life Pools and Algeth'ar to test.  When I zone in without LoggerHead, no errors.  When I zone into a new difficulty for the first time, I get the issue described above, where the popup doesn't go away when clicking on one of the options, _and clicking the Enable button_ causes the following error:
```
1x ...eBlizzard_CombatText/Blizzard_CombatText.lua:448: attempt to compare two nil values
[string "@Blizzard_CombatText/Blizzard_CombatText.lua"]:448: in function <...eBlizzard_CombatText/Blizzard_CombatText.lua:429>
[string "=[C]"]: in function `CombatText_AddMessage'
[string "@LoggerHead/Libs/LibSink-2.0-100000/LibSink-2.0.lua"]:399: in function `func'
[string "@LoggerHead/Libs/LibSink-2.0-100000/LibSink-2.0.lua"]:532: in function <...eLoggerHead/Libs/LibSink-2.0/LibSink-2.0.lua:518>
[string "@LoggerHead/Libs/LibSink-2.0-100000/LibSink-2.0.lua"]:538: in function `Pour'
[string "@LoggerHead/Loggerhead.lua"]:325: in function `EnableLogging'
[string "@LoggerHead/Loggerhead.lua"]:306: in function `Update'
[string "@LoggerHead/Loggerhead.lua"]:242: in function `ForceUpdate'
[string "@LoggerHead/Loggerhead.lua"]:276: in function `accept'
[string "@LoggerHead/Loggerhead.lua"]:103: in function <LoggerHead/Loggerhead.lua:100>

Locals:
message = "Combat being logged to Logs/WoWCombatLog"
scrollFunction = <function> defined @Blizzard_CombatText/Blizzard_CombatText.lua:644
r = 1
g = 1
b = 1
displayType = nil
isStaggered = false
string = CombatText1 {
 scrollTime = 0
 scrollFunction = <function> defined @Blizzard_CombatText/Blizzard_CombatText.lua:644
 0 = <userdata>
}
noStringsAvailable = nil
yDir = nil
lowestMessage = nil
useXadjustment = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = 1
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare two nil values"
```

When I log into a dungeon that I've previously enabled logging for, LoggerHead does not successfully enable logging and I get the following error:
```
49x ...eBlizzard_CombatText/Blizzard_CombatText.lua:448: attempt to compare two nil values
[string "@Blizzard_CombatText/Blizzard_CombatText.lua"]:448: in function <...eBlizzard_CombatText/Blizzard_CombatText.lua:429>
[string "=[C]"]: in function `CombatText_AddMessage'
[string "@Rarity/Libs/LibSink-2.0-100000/LibSink-2.0/LibSink-2.0.lua"]:399: in function `func'
[string "@Rarity/Libs/LibSink-2.0-100000/LibSink-2.0/LibSink-2.0.lua"]:532: in function <.../Rarity/Libs/LibSink-2.0/LibSink-2.0/LibSink-2.0.lua:518>
[string "@Rarity/Libs/LibSink-2.0-100000/LibSink-2.0/LibSink-2.0.lua"]:538: in function `Pour'
[string "@Rarity/Core/Interoperability/LibSink/Output.lua"]:6: in function `DisplayText'
[string "@Rarity/Core/GUI/FauxAchievementPopup.lua"]:138: in function `ShowFoundAlert'
[string "@Rarity/Core/EventHandlers.lua"]:718: in function `OnItemFound'
[string "@Rarity/Core/EventHandlers.lua"]:1010: in function `ProcessOtherItem'
[string "@Rarity/Core/EventHandlers.lua"]:946: in function `ProcessInventoryItems'
[string "@Rarity/Core/EventHandlers.lua"]:1103: in function <Rarity/Core/EventHandlers.lua:1076>
[string "=[C]"]: ?
[string "@Rarity/Libs/AceBucket-3.0-4/AceBucket-3.0.lua"]:69: in function <...eRarity/Libs/AceBucket-3.0/AceBucket-3.0.lua:67>
[string "@Rarity/Libs/AceBucket-3.0-4/AceBucket-3.0.lua"]:83: in function `func'
[string "@AllPlayed/libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <AllPlayed/libs/AceTimer-3.0/AceTimer-3.0.lua:48>
```
This error seems to have nothing to do with LoggerHead, but it doesn't happen when LoggerHead is disabled and specifically happens when LoggerHead is trying to enable combat logging.  When I log into dungeons where combat logging is _not_ enabled, but LoggerHead is, there are no errors.

Since both errors seem to have to do with outputting a message to Blizzard combat text that would let me know that LoggerHead has started logging, here's a screenshot of my LoggerHead - Output options:
https://i.imgur.com/8rnEGAd.png

**Comment by aa-chrismcfadyen** [comment]
After making sure that was all correct, I then chose one of the output options and there's no longer an error.  I'm not sure how it got into that state (I don't remember uninstalling anything that was a valid output before; I'm pretty sure I've always had it set to None because I rely on an LDB display to know if it's enabled or not), but there's no problem now.
