### ISSUE TITLE
Logging stops after each boss

### ISSUE THREAD

**Issue by YetAnotherDevWannabe** [dratr/loggerhead#5]
Title.
In Amirdrassil my log stop after every boss kill and I don't know why. And it pisses me the hell off.
I have the Raider.io client with logging on, tried turning it off but it didn't hcange anything. I also have the option turned on for advanced combat logging in Wow.

Please help me

**Comment by dratr** [comment]
I cannot reproduce this;  it is likely another addon is adjusting the Wow client logging status if you are seeing behavior like this as the addon doesn't adjust logging per boss, only per instance.
Try with other addons disabled; if that fixes it, you can reenable others until you find the culprit.

**Comment by YetAnotherDevWannabe** [comment]
It's likely an incompatibility since after disabling only LoogerHead, it works as intended.
If I do find the incompatibility I'll update you :)
