### ISSUE TITLE
release 11.0.0 switches to classic from mainline

### ISSUE THREAD

**Issue by torkus** [dratr/loggerhead#6]
Is this change from mainline to classic intentional or should `11000` be `110000`?

https://github.com/dratr/loggerhead/compare/10.2.5...11.0.0#diff-de6fdd8d56b0b83b17c091bdaf5a1a1ab907762e00ee6d5f6c445f28877fca83R1

**Comment by dratr** [comment]
Thanks for pointing this out!  Absolutely not intentional.  I have pushed out another release with the corrected interface version.
